Fix parse new build warnings
patrick-rivos/gcc-postcommit-ci pull request #1273
Opened 2024-07-03 17:50 UTC by kevinl-rivosinc

Modify the download-all-build-artifacts action to replicate download-all-comparison-artifacts to search both the current workflow and other workflows for a specified artifact.

Moreover, revert the reverted use of parse new build warnings script.

2024-07-09 20:46 UTC, patrick-rivos requested changes

2024-07-09 20:46 UTC, patrick-rivos commented on .github/actions/download-all-build-log-artifacts/action.yaml
> +      uses: ./.github/actions/common/download-build-log-artifacts
This action does not exist.

2024-07-16 18:31 UTC, patrick-rivos approved these changes
LGTM with a clean staging run

2024-07-16 18:51 UTC, ewlu approved these changes

2024-07-18 01:05 UTC, merged